backend:
  name: git-gateway
  branch: master

media_folder: "/public/static/images"
public_folder: "/static/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "data/blog/"
    create: true
    fields:
    - {label: "Slug", name: "slug", widget: "string", require: true}
    - {label: "Title", name: "title", widget: "string", require: true}
    - {label: "Date", name: "date", widget: "datetime", format: "MM/DD/YYYY", require: true}
    - {label: "Tags", name: "tags", widget: "string", require: true}
    - {label: "Last Modified", name: "lastmod", widget: "datetime", format: "MM/DD/YYYY", require: false}
    - {label: "Draft", name: "draft", widget: "boolean", default: false, require: false}
    - {label: "Summary", name: "summary", widget: "text", require: true}
    - {label: "Images", name: "images", widget: "string", require: false}
    - {label: "Authors", name: "authors", widget: "string", require: true}
    - {label: "Canonical Url", name: "canonicalUrl", widget: "string", require: false}
    - {label: "Body", name: "body", widget: "markdown"}
  - name: "author"
    label: "Author"
    folder: "data/authors"
    create: true
    fields:
    - {label: "Slug", name: "slug", widget: "string", require: true}
    - {label: "Name", name: "name", widget: "string", require: true}
    - {label: "Avatar", name: "avatar", widget: "string", require: true}
    - {label: "Occupation", name: "occupation", widget: "string", require: true}
    - {label: "Company", name: "company", widget: "string", require: true}
    - {label: "Email", name: "email", widget: "string", require: true}
    - {label: "Facebook", name: "facebook", widget: "string", require: true}
    - {label: "Github", name: "github", widget: "string", require: true}
    - {label: "About", name: "body", widget: "markdown"}
